### ISSUE TITLE
Expand Camera Area

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/aurora#1375]
<img width="1509" alt="image" src="https://github.com/acm-ucr/hackathon-website/assets/36285610/4417a494-f692-4d28-8725-309df4c2041a">

- Camera area becomes limited on smaller screens, there is nothing else on this screen so we can use it up with more room for the camera

**Comment by jonlachlan** [comment]
The parent component ProtectedPage has a class "w-11/12" that is affecting the size. Is it okay to remove this class from the parent component? That makes it look better. See pic.
![check-in](https://github.com/acm-ucr/hackathon-website/assets/2972585/c33fa900-d890-45ce-af3b-281d4d3ff310)

If other components need the w-11/12 class then I think it would be better to have them include the class directly on their highest level div, rather than including the class for the parent component ProtectedPage.
